### ISSUE TITLE
Les clés des objets affiches un tiret au lieu de deux-points

### ISSUE THREAD

**Issue by Codain** [Magellium/magOSM#1]
Sur la carte, en activant par exemple la couche `Police et gendarmerie` et en cliquant sur un des ronds bleus, on peut voir les clés suivantes : 

- ref-FR-GendarmerieNationale
- police-FR

Or les vrais clés sont avec des deux-points : 

- ref:FR:GendarmerieNationale
- police:FR

Idem, les liens vers Taginfo utilisent des tirets. au lieu de deux-points.

Il serait souhaitable d'afficher les vrais clés, c'est-à-dire avec des deux-points.

**Comment by ddespres** [comment]
Merci pour ce retour, nous allons corriger ça prochainement.

**Comment by ddespres** [comment]
c'est corrigé au niveau de l'affichage dans la fenêtre d'information. En revanche au téléchargement des données via WFS, le noms des attributs contiendra encore des -
