### ISSUE TITLE
permalink does not work...

### ISSUE THREAD

**Issue by u4y0u** [Magellium/magOSM#3]
Hello, the permalink does not work and leads to a blank page ...
I tried to use this link with Firefox 77:
[https://magosm.magellium.com/portail/#/carte?z=14&lon=-1.7721&lat=46.5001&tr=70&vLay=france_telecom_copper_connection_point,france_telecom_fibre_connection_point,france_telecom_exchange_point](url)

**Comment by audour** [comment]
Hi, 
Thanks @u4y0u for issue and sorry for delay !
Yes permalink is broken, we plan to fix it ASAP but for now we've just hidden the functionnality to avoid confusion.

**Comment by u4y0u** [comment]
👌 Thanks

**Comment by audour** [comment]
https://github.com/Magellium/magOSM/commit/1e20239c3f65420363a551f633d5ed37d58519a9 and https://github.com/Magellium/magOSM/commit/0e383d5d2f5aece07ef07cb900ef2e7d05f445be close the issue
